TOKEN = 'YOUR_TELEGRAM_BOT_TOKEN'
SOL_WALLET_ADDRESS = 'YOUR_SOL_WALLET_ADDRESS'
BARK_WALLET_ADDRESS = 'BARK1X2VgwF1auwH6NzwLgXcAuMzrGnfsssAxaMczJLV'
SOL_PAYMENT_AMOUNT = 1  # Amount in SOL required to join
BARK_PAYMENT_AMOUNT = 100000  # Amount in BARK required to join
SOLANA_RPC_URL = "https://api.mainnet-beta.solana.com"

# BARKERs Club Membership Tiered CNFT Settings
CNFT_API_URL = 'https://api.mainnet-beta.solana.com'
CNFT_PROSPECT_TIER_TOKEN = 'PROSPECT_TOKEN_ID'
CNFT_FULL_MEMBER_TIER_TOKEN = 'FULL_MEMBER_TOKEN_ID'
CNFT_VETERAN_MEMBER_TIER_TOKEN = 'VETERAN_TOKEN_ID'
CNFT_SOLDIER_TIER_TOKEN = 'SOLDIER_TOKEN_ID'
